app.id=sql-migration-app
app.version=1.0.0
app.release=dev
app.name=SQL Migration Service
app.group=Development/Services
app.summary=SQL Migration Service
app.url=https://suvera.github.io/
app.license=MIT

company.name=Suvera
company.id=suvera